const ITEM_PRICES = {
  "Amulett der Heilung" : 5,
  "Amulett der Feuersbrunst" : 6,
  "blauer Saphir": 277,
  "Beutezauber": 17,
  "Blutzauber der Schwächung": 40,
  "blaue Perle des Wissens": 70000,
  "Buch der Amulettkunde": 250,
  "Buch der Angriffsenergie": 100,
  "Buch der Auftragsbeziehungen": 250,
  "Buch der Auftragsplanung": 500,
  "Buch der Auftragsvertuschung": 1.000,
  "Buch der Chaosbotanik": 15,
  "Buch der Chaosmagie": 180000,
  "Buch der Furchtinspiration": 500,
  "Buch der Getreideverarbeitung": 420,
  "Buch der Gewebeanalyse": 500,
  "Buch der Gewebeforschung": 500,
  "Buch der Gold-Inspiration": 50,
  "Buch der Großwildjagd": 130000,
  "Buch der Gruppenheilung": 100,
  "Buch der Handwerkskunst": 250000,
  "Buch der inneren Macht": 500,
  "Buch der Inspiration": 20,
  "Buch der Jagd": 420,
  "Buch der Kochkunst": 350,
  "Buch der Labortechnik": 80000,
  "Buch der Lagerlogistik": 3000,
  "Buch der Lebensenergie": 300,
  "Buch der Leichenfledderei": 10000,
  "Buch der Lerntechnik": 500,
  "Buch der Magieverlängerung": 2000,
  "Buch der Marktwirtschaft": 250,
  "Buch der Meteorologie": 1250,
  "Buch der Pflanzenkunde": 50000,
  "Buch der Phasenenergieeffizienz": 250,
  "Buch der Phasenenergiemaximierung": 10000,
  "Buch der Phasenenergiespeicherung": 200,
  "Buch der Phasenwebkunst": 180000,
  "Buch der Plünderung": 480,
  "Buch der Polarisationsanpassung": 250,
  "Buch der Rache": 25,
  "Buch der Schatzjagd": 2070,
  "Buch der Schusswaffen": 600,
  "Buch der Seelenverbindung": 100000,
  "Buch der Selbstheilung": 1500,
  "Buch der Siegelringkontrolle": 100000,
  "Buch der Synergie-Inspiration": 10000,
  "Buch der Verteidigungskraft": 75000,
  "Buch der Waffenkunst": 200,
  "Buch der Wissens-Inspiration": 50,
  "Buch der Zauberalchemie": 1,
  "Buch der Zauberkunst": 25,
  "Buch der Zeit-Inspiration": 50,
  "Buch der Ölverwaltung": 1000,
  "Buch der Überzeugungskraft": 450,
  "Buch des Ausgrabungswissens": 50,
  "Buch des Bankwesens": 50,
  "Buch des Bauwesens": 3000,
  "Buch des Blutwissens": 250,
  "Buch des Diebstahlschutzwissens": 480,
  "Buch des DurchhaltevermÖgens": 500,
  "Buch des Fliegens": 150,
  "Buch des Geisterflugs": 2500,
  "Buch des Glücks": 100,
  "Buch des Goldabbaus": 300,
  "Buch des Goldraubs": 50,
  "Buch des Lebenstrainings": 500,
  "Buch des Mutationswissens": 300,
  "Buch des Phasenverständnisses": 5000,
  "Buch des Reparaturwissens": 300,
  "Buch des Stärketrainings": 400,
  "Buch des Verjagens": 250,
  "Buch des Vertreibens": 500,
  "Buch des Zaubertresorwissens": 50,
  "Buch des Zaubertruhenwissens": 200000,
  "bunte Bunnyköttel": 1,
  "Bunte Pflanzensamen": 1,
  "buntes Ei": 8,
  "Buntes Osterei": 5,
  "Buraner Schlachtplatte": 5,
  "Bücherbusausweis": "?",
  "Bücherregal": 10,
  "Bündel weißer Rosen": 0,
  "Büschel Hirschfell": 0,
  "Chaossense": 25,
  "Chaosstaub": 0,
  "chaotische Sandsphäre": 25000,
  "Clan-Blitzschild": 85,
  "Clan-Heilzauber": 1461,
  "Clan-Herzauber": 110,
  "Clan-Hinzauber": 80,
  "Clan-Itemteleportation": 8,
  "Clan-Kampfunfähigkeitszauber": 170,
  "Clan-Phasenüberladung": 153,
  "Clan-Seelenkapsel": 41,
  "Clanfeind-Tarnauflösung": 2,
  "Cocktail aus der Schwarzbrauerei": 16,
  "Cocktail von Beispielsponsor": 16,
  "Cuslarsmaragd": 150,
  "Dampfkanone": 775,
  "defekte Portalmaschine": 35000,
  "Deutschland-Trikot (W11)": 14,
  "Deutschlandflagge zur EM 2008": 15,
  "Diamantharnisch": 17000,
  "Diamantspitze": 0,
  "dicker, fetter Larafkuchen": 8,
  "Diebstahlfalle": 5,
  "Diebstahlschutzzauber": 2560,
  "Diebstahlzauber": 150,
  "Dolch": 130,
  "Dolch der Auftragsmörder": 500,
  "Donnerluftschlange": 4,
  "Doppelaxt": 500,
  "Dornblatt-Anzug": 510,
  "Dornenstrauch": 9,
  "dreckige Wolle": 1,
  "dreckiger Glitzerklumpen": 0,
  "drehendes Zeitglas": 100,
  "Drehscheibe der inneren Macht": 10000,
  "Drucknuss": 1,
  "Druckwelle": 100,
  "Duft der XY-Wesen": 53,
  "Dunkelgrottenmoos": 500,
  "Dunkelmorin-Fell": 350,
  "Dunkelschattenblume": 35,
  "Dunkelscheinbeeren": 8,
  "Dunkelstern-Staub": 85,
  "dunkle Eisenstrebe": 20,
  "dunkle Kontrolle": 450,
  "dunkle Magier-Robe": 690,
  "dunkler Heilzauber": 17,
  "dunkler Ring des Schutzes": 720,
  "dunkler Sockel": 155,
  "dunkles Armband": 400,
  "Dunkles Kleid": 4900,
  "Durchgang": 5,
  "durchgeknallter Nebelkristall": 500,
  "durchschlagende Armbrust": 5400,
  "Dydromonia": 56,
  "Dynamitstangen": 150,
  "Dämon des Schutzes": 17000,
  "Dämonenblut": 7,
  "Dämonenblutfass": 100,
  "dämonische Kugel": 100,
  "Dünger": 5,
  "düsterer Staub": 0,
  "Düsterfrostschimmel": 7,
  "Edelstein der Liebe": 277,
  "Edelstein des Lichts": 277,
  "Edles Trinkhorn": 25000,
  "effektiver Diebstahlzauber": 75,
  "effektiver Jerodar-Diebstahlzauber": 9,
  "Ehering": 6000,
  "Eimer mit Baru-Leim": 20,
  "Einfache Gruppen-Betörung der Geistlosen": 150,
  "einfache Holzangel": 0,
  "einfacher Eisenbogen": 600,
  "einfacher Holzbogen": 50,
  "Eisblume": 24,
  "Eisbonbon": "?",
  "Eisenerz": 1,
  "Eisenkralle": 120,
  "Eisenrankenrüstung": 8500,
  "Eisenschild mit Stacheln": 600,
  "Eisenzange": 9,
  "eiserne Hartplattenwand": 350000,
  "eiserne Schmerzschwinge": 1,
  "eiserne Schwingtrommel": 10,
  "eiserne Wand": 700000,
  "eisiger Teleporter": 400,
  "Eiskristall-Pulver": 20,
  "Eisrose": 7,
  "Eisstachel": 1,
  "Eiszauber": 5,
  "Ektofronstachel": 0,
  "Element-Knoten": 4000,
  "Elixier der Bewegung": 5,
  "Elixier der geistlosen Lebenssicht": 5,
  "Elixier der Gesundheit": 5,
  "energetische Beschwörung": 15,
  "energetische Betörung": 100,
  "energetische Chaoslabor-Scheibe": 8,
  "energetische Entstarrung": 7,
  "energetische Kontrolle der Zeit": 10,
  "energetische Sumpfgasbombe": 40,
  "energetische, globale Auferstehung": 150,
  "energetischer Heilzauber": 5,
  "energetischer Kampfunfähigkeits-Schutz": 15,
  "energetischer Portalzauber": 5,
  "energetischer Schutzzauber": 5,
  "Energetisches Drehgewinde": 25,
  "Energiekompass": 0,
  "Energiesphäre": 0,
  "Engel der Halsketten": 15,
  "Engel des Weines": 15,
  "Engel des Wissens": 15,
  "Erdbeben": 170,
  "Erdbeere": 222,
  "Erdstein": 25,
  "Essenz der Angst": 7,
  "Essenz der Atmosphäre": 425,
  "Essenz der Furcht": 350,
  "Etume-Enzian": 10,
  "Event-Item": 0,
  "explosive Sporenkapsel": 41,
  "Amulett der schwachen Erfahrung": 5,
  "Fackel des Auftragshauses": 0,
  "Fallenentschärfer": 0,
  "Fallengift": 10,
  "Falltür": 5,
  "Falsche Erfahrung": 5000,
  "Falterfangnetz": 0,
  "Falterflügel": 6,
  "faulige Birne": 0,
  "Federboa": 7,
  "Fell der Finsternis": 30,
  "Fels der Phasenselbstheilung": 30000,
  "Felsenwurmschild": 20,
  "Ferdolischer Bratapfel": 15,
  "Fernheilzauber": 5,
  "Fernschutzzauber": 25,
  "Fernzünder": 125,
  "fesselnder Wegzauber": 250,
  "festlicher Postvogel": 5,
  "feuchter Tonstein": 50,
  "Feuerball": 90,
  "Feuerdiamant": 5,
  "Feuerdolch": 10,
  "Feuereintopf": 5,
  "Feuerelement": 5333,
  "Feuerelement der Furcht": 8000,
  "Feuerkolben": 10,
  "Feuerkristall": 12,
  "Feuerperle": 150,
  "feuerrote Pflanzensamen": 1,
  "Feuerstab": 500,
  "Feuerstein": 9,
  "Feuersturm": 1000,
  "Feuerwalze": 800,
  "Feuerwerksrakete": 80000,
  "Feuerwolke": 250,
  "Feuerzunge": 25,
  "Feueröl": 14,
  "feurige Sandaxt": 5333,
  "feurige Sandaxt der Furcht": 8000,
  "Feuriger Torponschuppenpanzer": 100000,
  "Feuriges Ornament": 1000,
  "Filetiermesser der Untiefen": 100,
  "Finsterbrause aus der Schwarzpanscherei": 16,
  "Finsterbrause von Beispielsponsor": 16,
  "Finstereis-Schild": 400,
  "Finstereis-Tropfen": 250,
  "Finstereisstaude": 25,
  "Fischsuppe": 5,
  "Fischtasche": 500,
  "flammender Geisterschild": 10000,
  "Flammendes Echsenbein": 1,
  "Flammenwurmsekret": 0,
  "flammloser Kleisterschild": 250,
  "Flasche Fledermausbier (W11)": 0,
  "Flasche mit Koloa-Käfer Gift": 0,
  "Flasche Sumpfgas": 40,
  "Flasche Taunektarbier": 10,
  "Fleegras": 30,
  "Fleischblume": 15,
  "Fluch des Gebrechens": 9,
  "Flugmaschine": 50000,
  "Flöte der Beförderung": 50,
  "Flöte der gezielten Beförderung": 10,
  "Flöte der tanzenden Sterne": 50,
  "Flügelpanzer": 540,
  "Flügelrüstung": 600,
  "Flüstertulpe": 500,
  "Foliant der XY-Wesen": 250,
  "Foliant der seltsamen Wesen": 250,
  "Foliant seltsamer XY-Wesen": 250,
  "Foliantenpult": 10,
  "Forschauge": 5,
  "Forschungssalz": 0,
  "Forschungssalz der XY-Mutation": 0,
  "Fossile Erzrose": 10,
  "Fremdartiges Erbgut": 10,
  "Freundschaftsring": 2000,
  "Frost-Farn": 50,
  "Frost-Wiesel-Anlocker": 2400,
  "Frostaugenschild": 5,
  "Frostbrand": 0,
  "Frostfeuerklinge": 5,
  "frostige Aura": 250,
  "frostige Seelenklinge": 10000,
  "funkelnder, blauer Heilzauber": 12,
  "funkelndes Donnerschwert": 5333,
  "funkelndes Donnerschwert der Furcht": 8000,
  "Funkelsalzstern": 4,
  "Funkenbrenner": 8000,
  "Furgorpilz": 3,
  "Futterschale (Einrichtungsgegenstand)": 5,
  "Futterschale": 20,
  "Fw -Überraschungsei": 0,
  "fürchterliche Maske": 0,
  "Gardusaft aus der Schwarzpanscherei": 16,
  "Gardusaft von Beispielsponsor": 16,
  "garnierter Kuhkopf": 5,
  "gebackene Gardubeeren": 13,
  "geborstener Stab der Lebensenergie": 10,
  "gebratenes Kaktusfleisch": 5,
  "Gebrochener Siegelring": 1111,
  "Geburtstagsplätzchen": 5,
  "Gefrorene Kugel": 2,
  "Gegengift": 80,
  "Gegenzauber: Angriff": 1,
  "Gegenzauber: Auflösung des Schutzes": 1500,
  "Gegenzauber: Diebstahl": 1,
  "Gegenzauber: Erfahrungsverlust": 200,
  "Gegenzauber: ferne Reinkarnation": 24,
  "Gegenzauber: Itemverlust": 100,
  "Gegenzauber: Kaktuspfeil": 200,
  "Gegenzauber: Kampfunfähigkeit": 0,
  "Gegenzauber: Kampfunfähigkeit (AF)": 1250,
  "Gegenzauber Starre": 200,
  "Gegenzauber: Vergessen": 10,
  "Geheimnisvoller Schlitten": "?",
  "Geisteressenz": 13,
  "Geisterfunke": 1,
  "Geisterkugel": 5000,
  "Geistersauger": 0,
  "Geisterschild": 10000,
  "Geistersiegel": 0,
  "geklebte, gelbe Zauberkugel": 25,
  "Gelbe Karte (W11)": 5,
  "Gelbe Schriftrolle": 0,
  "Gelbe Zauberkugel": 5,
  "gelber Prisma-Kristall": 100,
  "gelber Ring des Schutzes": 800,
  "gelbes Ingeriumsulferat": 500,
  "Gelbes Osterei": 5,
  "Gelbohrschweinchen": 0,
  "Gelbpollenschleuder": 500,
  "Gelbsternschmarotzer": 10,
  "Gelbsäure": 10,
  "Geldbeutel": 0,
  "gelöstes Klebeöl": 11500,
  "gelöstes Pappgas": 5000,
  "Genervte Weihnachtsfrau": 10,
  "gepresste Zauberkugel": 25,
  "gerösteter Schleimhautfisch": 0,
  "gesalzene Gewebeprobe": 0,
  "Geschenk mit Schleife": 1,
  "Geschenk von Beispielsponsor": 0,
  "geschliffener Hartplattenstein": 20,
  "Gesichtscreme": 0,
  "gesockelter Prisma-Kristall d. Erfahrung": 500,
  "gesockeltes Prisma der Frostkälte": 5000,
  "gesockelter Prisma-Kristall der Heilung": 500,
  "gesockelter Prisma-Kristall der Zeitkontrolle": 500,
  "gesockeltes Prisma der Feuerbrunst": 500,
  "gesockeltes Prisma der Genesung": 500,
  "gesockeltes Prisma der Vergiftung": "?",
  "gesockeltes Prisma des Wissens": 500,
  "Gespaltenes Haar": 25,
  "gestampfte, rote Zauberkugel": 25,
  "gewaltiger Phasenstrahler": 25000,
  "Gewebefetzentotem": 5,
  "Gewebeprobe von XY": 5,
  "Gewebewurm": 30,
  "Gewebewurm im Brot": 5,
  "gewundener Draht": 5,
  "gewöhnliche Bronzephiole": 65,
  "Gewürzbohnen": 5,
  "Geysir-Stein": 250,
  "Gib-mich-weiter-Blume": 0,
  "Gießkanne": 10000,
  "Gift gegen Einflügler": 0,
  "Gift gegen Geysir-Schlucker": 0,
  "Giftblattrüstung": 600,
  "Giftdolch der Händler": 775,
  "Giftfalle": 1,
  "Giftige Tropfen": 0,
  "giftiger Müll": 0,
  "giftiger Wurzeldolch": 5333,
  "giftiger Wurzeldolch der Furcht": 8000,
  "Giftnadelkeule": 775,
  "Giftperle": 5,
  "Giftspritze": 0,
  "Giftstachelbusch": 620,
  "Giftstachelkatapult": 800,
  "Giftwucherknolle": 4,
  "gigantische Seelenkapsel": 5,
  "Gipfellöwenzahn": 125,
  "Glas mit Sternenfunken": 0,
  "Glas voller Grafrather Stechmücken": 100,
  "Glassplitter": 5,
  "Glimmerbrocken": 11,
  "Glimmerspäne": 0,
  "Glitzer-Cocktail": 8,
  "glitzerndes Öl": 1000,
  "globale Auferstehung": 350,
  "globale Betörung": 500,
  "globale Goldflut": 150,
  "globale Gruppen-Auferstehung": 100,
  "globaler Geldregen": 50,
  "Globaler Heilzauber": 50,
  "globaler Schutz der Geistlosen": 50,
  "Schneeschaufel": 0,
  "globaler Schutzzauber": 100,
  "globaler Verwirrungszauber": 100,
  "Glodo-Fisch": 5,
  "Glutschleimauge": 50,
  "Glücks-Ei": 1,
  "glühender Feuerkolben": 20,
  "glühender Feuerstein": 8,
  "Glühender Stock": 90,
  "Glühendes Suphasglas": 350,
  "Glühwein": 16,
  "Goldbarren": 500,
  "Golddiadem": 1500,
  "Goldene Akte von Beispielspieler": 500,
  "goldene Flöte der Beförderung": 20000,
  "goldene Hundemarke": 378,
  "goldene Jerodar-Halskette": 2500,
  "goldener Armreif": 350,
  "Goldener Gewebewurm": 50,
  "Goldener Kuhdarm": 150,
  "Goldener Löffel": 0,
  "goldener Schlüssel": 28,
  "goldener Talisman": 0,
  "Goldener Torponschuppenpanzer": 100000,
  "goldener Zaubertopf": 15000,
  "Goldenes Ei": 5,
  "goldenes Schmuckstück": 1,
  "Goldenes Tirrebmetall": 350,
  "goldenes Zahnrad": 495,
  "Goldfaden": 50,
  "Goldfeder": 4,
  "Goldflosse": 15,
  "Goldkrebspanzer": 20,
  "Goldnugget": 35,
  "Goldplattenschild": 500,
  "Goldschwert": 500,
  "Goldsonnen-Blümchen": 60,
  "Goldstaub": 100,
  "Goldtropfen": 50,
  "Goldwäschesieb": 80,
  "Goldwürfel": 30000,
  "Gonholzstock": 8,
  "Grasbüschel": 0,
  "grauer Indikator": 350,
  "Grefek-Perle": 250,
  "Große Pastille der Ansteckung": 2,
  "Große Pastille der Clan-Energie": 25,
  "Große Pastille der Heilung": 2,
  "Große Pastille der Herbeirufung": 2,
  "Große Pastille der Phasenenergie": 2,
  "Große Pastille der Phasenrisse": 2,
  "Große Pastille der Schreckensblitze": 2,
  "Große Pastille der Schreckensblumen": 2,
  "Große Pastille der Schärfung": 2,
  "Große Pastille der Seelensicht": 2,
  "Große Pastille der Zeitkontrolle": 2,
  "Große Pastille des Fliegens": 2,
  "Große Pastille des Wissens": 2,
  "Grottenschlangenhaut": 1000,
  "große Axt": 450,
  "große Reparatur-Zange": 5,
  "große Schriftrolle der Lebenden": 1,
  "große Seelenkapsel": 0,
  "große Zauberkugel": 25,
  "großer Blumenstrauß": 80,
  "großer Energiesplitter": 8,
  "Großer Geldbeutel": 0,
  "großer Heiltrank": 23,
  "großer Holzstock": 150,
  "großer Larinit-Klumpen": 150,
  "großer Phasentrank": 3,
  "Großer Sandschild": 200,
  "großer Sandstock": 50,
  "großer Seelentrank": 30,
  "großer seltsamer Trank": 2,
  "großer Skorpionstachel": 125,
  "großer Trank der Nordpolarisierung": 5,
  "Gruppen-Beschwörung der Geistlosen": "?",
  "Gruppen-Betörung der Geistlosen": "?",
  "Gruppen-Hinzauber": 17,
  "Gruppen-Schutzzauber": 25,
  "Gruppen-Seelenkugel": 25,
  "Gruppenheilzauber": 10,
  "Gruppenherzauber": 15,
  "Grymholz": 1,
  "Grün grinsender Nikolaus": 5,
  "Grüne Schriftrolle": 0,
  "grüne Zauberkugel": 5,
  "grüne, eingestellte Zauberkugel": 5,
  "grüner Baru-Schleier": 10000,
  "Grüner Daumen": 7,
  "grüner Giftschleim": 0,
  "grüner Ingeriumsplitter": 2,
  "Grüner Kugelschneider": 270000,
  "grüner Prisma-Kristall": 100,
  "grüner Ring des Schutzes": 1050,
  "grüner Smaragd": 277,
  "grüner Stein der Selbstheilung": 80000,
  "grüner Zauberkugelindikator": 50,
  "grünes Baru-Schwert": 10000,
  "Grünes Osterei": 5,
  "Grünes Torponschlangenei": 50,
  "Gula-Nüsse": 5,
  "Gussform": 1,
  "halb verdautes Steak mit Augen": 1,
  "Halloween Kürbis": 1,
  "Halloween-Bowle (W11)": 0,
  "Halloween-Maske": 10,
  "Halterungsrahmen": 20,
  "Hammer des Auftragshauses": 0,
  "Hartplattenstein": 25,
  "Hartrindenschild": 1000,
  "Harzbaumschild": 1030,
  "Hase Franz": 5,
  "Hase Fritzchen": 5,
  "Hase Harald": 5,
  "Hase mit Osterei": 5,
  "Hase Rudi": 5,
  "Hasenfell": 10,
  "Hasenfell-Zahnseide": 5,
  "Hautbrand": 60,
  "heilender Baum": 0,
  "Heilender Regen": 30,
  "heilender Schlamm": 28,
  "Heilzauber": 16,
  "Heilzauber der Geistlosen": 0,
  "Heimzauber": 10,
  "Heiße Lava": 2,
  "Heißer Weihnachtsengel": 4,
  "Heller Oktaeder": "?",
  "Helm des Lichts": 600,
  "Helm des Serums": 480,
  "Helmkrone": 5,
  "Herbeirufung der Geistlosen": 30,
  "Herz eines Glypra": 0,
  "Herzauber": 90,
  "Heuballen": 2,
  "Hinzauber": 200,
  "Hinzauber zu Beispielspieler": 100,
  "Hirtenstab": 8,
  "hochenergetische Beschwörung": 15,
  "hochenergetische Betörung": 250,
  "Hochzeitsanzug": 7000,
  "Hochzeitskleid": 7000,
  "Holz": 1,
  "Holzarmbrust der Erfahrung": 1200,
  "Holzgefäß": 0,
  "Holzleiter": 110,
  "Honigmilch aus der Schwarzmolkerei": 16,
  "Honigmilch von Beispielsponsor": 16,
  "Horn aus Bernstein": 500,
  "Horn der Sontra Fahr": 0,
  "Horn des Teidams": 150,
  "Hulnodar-Kellerschlüssel": 10,
  "Hundekäfig": 0,
  "Hörnchen des Teidam-Babys": 100,
  "Ingerium": 60,
  "Ingeriumplatte": 0,
  "Insektenspray gegen Koloa-Käfer": 0,
  "Instabile Betörung": 100,
  "instabile, globale Auferstehung": 350,
  "Instabiler, globaler Schutzzauber": 150,
  "Irrer Wichtel": 5,
  "Itemschleuder": 15000,
  "Itolos-Felsenwicke": 5,
  "Itolos-Leder": 0,
  "Itolos-Leder-Imitat": 0,
  "Itolos-Pulver": 50,
  "Jerodar-Diebstahlzauber": 3,
  "juwelenbesetzter Goldbarren": 1500,
  "Juwelenring von Gruan": 0,
  "Kakao aus der Schwarzbrüherei": 16,
  "Kakao von Beispielsponsor": 16,
  "Kaktusfleisch": 12,
  "Kaktuspfeil": 40,
  "Kaktuspfeilschleuder": 700,
  "Kaktussaft aus der Schwarzpanscherei": 16,
  "Kaktussaft von Beispielsponsor": 16,
  "Kamelle": 5,
  "Kampfgebiet - Enttarnung": 10,
  "Kampfgebiet - Heiltrank": 9,
  "Kampfgebiet - Schutzauflösung": 12,
  "Kampflibelle": 5333,
  "Kampfplatz": 10,
  "Kampfunfähigkeits-Schutz": 55,
  "Kampfunfähigkeitszauber": 120,
  "Kanalisationsrechen": 0,
  "Kandierter Apfel": "?",
  "Kapsel der Clan-Energie": 8,
  "kaputte Phasenlanze": 100,
  "kaputter Helm des Lichts": 155,
  "kaputter Ring des Todes": 155,
  "kaputter roter Ring": 155,
  "Karamellgräte": 2,
  "Karte der Unterkunft": 0,
  "Katzenkäfig": 0,
  "Kern der Vernichtung": 25,
  "Kern der Zähigkeit": 25,
  "Kette der Raumzeit": 42,
  "Kette der unsäglichen Kraft": 42,
  "Kettenamboss": 5333,
  "Kettenamboss der Furcht": 8000,
  "Kettenglied": 5,
  "Keuronium": 1,
  "Kiste mit Gegengift": 0,
  "Kiste mit Lebendfutter": "?",
  "Kiste mit Reagenzgläsern": 0,
  "Kiste mit Taunektarbier": 55,
  "Klauenbartrein-Burger": 5,
  "Klebefalle": 2,
  "klebrige Flöte der Beförderung": 1375,
  "Klebriges Stückchen": 50,
  "kleine Armbrust des Lebens": 1800,
  "kleine Bronzephiole": 100,
  "kleine Zauberkugel": 10,
  "Kleiner Anhänger": 25,
  "kleiner Beutel mit Pflanzensamen": 0,
  "kleiner Blumenstrauß": 36,
  "kleiner Bonsai-Laraf": 1,
  "kleiner Energiesplitter": 2,
  "Kleiner Geist": 1,
  "kleiner Heiltrank": 16,
  "Kleiner Holzschild": 30,
  "kleiner Holzstock": 10,
  "kleiner Keil": 10,
  "kleiner Kellerschlüssel": 15,
  "kleiner Larinit-Klumpen": 100,
  "Kleiner Sandschild": 80,
  "Kleiner Sandstock": 2,
  "kleiner Seelentrank": "?",
  "Kleiner Serum-Schild": 30,
  "Kleines Holzgerüst": 20,
  "Kleines Nikolausteidam": 8,
  "Kleines Osternest": 8,
  "Klopfstock": 0,
  "Knallbunte Vuvuzela": 15,
  "Knallforsch": 10,
  "Knallgrünes Osterei": 5,
  "Knallpunsch": 0,
  "Knochen": 20,
  "Knochenklinge": 5333,
  "Knochenpulver": 11,
  "Knorpel-Monster aus Draht": 5,
  "Knorpelhaut": 5,
  "knusprige Nolulawurzel-Stückchen": 5,
  "Kofinientee aus der Saline": 16,
  "Kofinientee von Beispielsponsor": 16,
  "Kokosnuss": 0,
  "Koloa-Bohne": 2,
  "Koloa-Kaffee": 2,
  "Koloa-Milch aus der Schwarzmolkerei": 16,
  "Koloa-Milch von Beispielsponsor": 16,
  "Koloa-Mühle": 18000,
  "Koloa-Schokolade mit Baru-Streuseln": 246,
  "komisches Eisenrohr": 60,
  "Kontrolle der Glypra": 50,
  "Kontrolle der Zeit": 100,
  "Kontrolle des Lichts": 2500,
  "Kopiermaschine": 10,
  "Korallen-Seelen-Misch-O-Mat": 800,
  "Korlad-Nuss": 4,
  "Korlad-Nuss-Samen": 2,
  "Korlad-Nuss-Trank": 2,
  "Krabbentorte": 450,
  "Kraftfaden": 5,
  "Kralle der Dunkelheit": 500,
  "Kralle des Weltenwandlers": 500,
  "Kreideperle der Lüfte": 50000,
  "Kreidestein": 5,
  "Kristall der Angst": 10,
  "Kristall der Heilung": 100,
  "Kristall der inneren Macht": 2500,
  "Kristall der Miniaturisierung": 2,
  "Kristall des Schmerzes": 100,
  "Kristallglas": 277,
  "Kristallknospe": 166,
  "Kristallschale": 25,
  "Kristallschmelze": 2500,
  "Kristallstab": 500,
  "Kristallwasseramulett": 5,
  "Kristallwasserherz": 25,
  "Kristallwurzel": 167,
  "Kroppkraut": 75,
  "Krustenkäferpanzer": 20,
  "Kräutergestein": 5,
  "Kräuterpastille": 4,
  "Kräutershake aus der Schwarzmolkerei": 16,
  "Kräutershake von Beispielsponsor": 16,
  "Kugelknochen": 0,
  "Kugelstampfer": 20000,
  "Kuhkopf": 5,
  "Kuschel-Stein": 7,
  "Kuss der Muse": 100,
  "Königlicher Schleifstein": "?",
  "Kübel mit frischer Milch": 0,
  "Kühlbox mit Gewebeproben": 0,
  "Landquallententakel": 10000,
  "langer Gewebewurm": 40,
  "Langzahn": 70,
  "Larafblüte": 25,
  "Larafkuchen": 8,
  "Larafpfeife": 55,
  "Larafsalat": 5,
  "Lareeer Dominostein der Illusion": 15,
  "Largudrübe": 18,
  "Largudsaft aus der Schwarzpanscherei": "?",
  "Largudsaft von Beispielsponsor": 16,
  "Largudseife": 200,
  "Larinit-Fackel": 30,
  "Larinit-Gussform": 100,
  "Larinit-Kleber": 1,
  "Larinit-Moos-Zucht": 3,
  "Larinit-Schlüssel": 0,
  "Larinitpilz": 25,
  "Laterne des Widerstands": 17000,
  "Lavapanzer": 15,
  "Leben der Geistlosen": 5,
  "lebende Erde": 10,
  "lebendes Farnblatt": 50,
  "lebendes Wasser": 10,
  "Lebendfutter": 100,
  "Lebendiger Torponschuppenpanzer": 100000,
  "Lebenserweiterung": 15,
  "Lebkuchenmännchen": "?",
  "Ledereinband": 111,
  "leere Bierflasche": 2,
  "leere Energiesphäre": 0,
  "leuchtender Gruftsäbel": 5333,
  "leuchtender Gruftsäbel der Furcht": 8000,
  "leuchtender Regenbogenstein": 0,
  "Lianenpeitsche": 130,
  "Likör": 1,
  "Lila Osterei": 5,
  "Linya-Orchidee": 45,
  "Liste der Clanfeinde": 1,
  "Loktit-Stein": 150,
  "Loktitfinder": 120,
  "Lopaknuss": 1,
  "Lopaknuss-Eis": 5,
  "Lopaknussschleuder": 500000,
  "Los": 20,
  "Madenstachel": 1,
  "Magiekristall": 5000,
  "Magische Christbaumkugeln": 4,
  "magische Eiskeule": 10,
  "magischer Beutel": 25,
  "magischer Giftstachel": 310,
  "magischer Zauberstock": 350,
  "magisches Holz": 1,
  "magisches Kopierlicht": 20,
  "magisches Kästchen": 15,
  "Magmalilie": 8,
  "Mammut-Kaktus": 20,
  "Mantel der Ablenkung": 250,
  "Mara-Knolle": 10,
  "Marke der Seelensucher": 0,
  "Marktstand (Einrichtungsgegenstand)": 0,
  "Marktverwalter": 5,
  "Massenherzauber": 15,
  "Massiver Holzgriff": 0,
  "mechanischer Bernstein-Falke": 500,
  "Mechanischer Steinzermahler": 0,
  "Meerwasser-Limo aus der Saline": 16,
  "Meerwasser-Limo von Beispielsponsor": 16,
  "Mehlsack": 1,
  "Meisterhammer": 10000,
  "meisterlicher Holzspreißel": 0,
  "Melkmaschine": 0,
  "Merkwürdiges Osterei": 5,
  "Messingwok": 44,
  "Messsender": 50,
  "Meterstab": 0,
  "Mirigardium": 0,
  "Mirigardium-Würfel": 2500,
  "Mister Lorper Halloween-Kostüm": 30,
  "Mondscheindiamant": 277,
  "Mondscheinrüstung": 17000,
  "Mondscheinschatulle": 800,
  "Mondscheintalisman": 5,
  "Mondstab": 5333,
  "Mondstab der Furcht": 8000,
  "Monobusch (Einrichtungsgegenstand)": 10,
  "Mooswurzel-Essenz": 5,
  "Morgenstern des Serum": 711,
  "mottenzerfressenes Kostüm": "?",
  "murmelnder Müllsortierer": 21,
  "Mutationssalz": 217,
  "Mysteriöses Lopaknussplätzchen": 15,
  "Mächtige Betörung der Geistlosen": "?",
  "mächtige Sicht der Diebesopfer": 25,
  "mächtiger Starreschutz-Zauber": 55,
  "mächtiger Wegzauber-Schutz": 55,
  "Mürbegras": 5,
  "nach Beispielrichtung zeigende Spuren des Äonenjägers": 0,
  "Nachtschatten-Lilie": 3,
  "Nacktbilder von Mister Lorper": 0,
  "Narrenkappe": 2,
  "Nasses Moos": 7,
  "Natlium": 0,
  "Nebel der Teleportation": 10,
  "Nebelanemone": 60,
  "Nebeldiadem": 50,
  "Nebelgold": 1500,
  "Nebelkaktus": 10,
  "Nebelkristall": 200,
  "Nebelmagnolie": 40,
  "Nebelschlauchwurz": 7,
  "Nebelschleuder": 5333,
  "Nebelschleuder der Furcht": 8000,
  "Nebelschwert": 1,
  "Nebeltee": 14,
  "Nebelwalflosse": 0,
  "Nesselfaden": 6,
  "Netz der Kopolaspinne": 15,
  "neuartiges Tierfutter": 0,
  "Neujahrskuchen": 0,
  "Nikolausi": 11,
  "Nikolaussocke": 2,
  "Nikolausteller": 15,
  "Nolulawurzel": 20,
  "Nossar-Strauch": 25,
  "Notizblock": 40,
  "Nudelholz": 12,
  "Nylfon-Magnet": 1,
  "Oktaeder der Helligkeit": 0,
  "Ölfass": 100,
  "Onlium": 1,
  "Onlium-Schlüssel": 10,
  "Onlo-Knochen": 20,
  "Onlo-Messer": 125,
  "Ontolon-Gehirn": 11,
  "Ontolon-Saugnapfschild": 400,
  "Orden des Sieges": 1,
  "Original Konlirer Christstollen": 15,
  "Oster-Cocktail": 8,
  "Oster-Ei": 1,
  "Oster-Phiole": 2,
  "Osterei": 1,
  "Osterhase (W5)": 4,
  "Osterhase (W7)": 4,
  "Osternest": 5,
  "Papierbeispiel-NPC": 2,
  "Parfum": 15,
  "Partielle, globale Auferstehung": 250,
  "Partyhut": 10,
  "Paste der Angst": 150,
  "Paste der Furcht": "?",
  "Pastille der Ansteckung": 2,
  "Pastille der Clan-Energie": 25,
  "Pastille der Heilung": 2,
  "Pastille der Herbeirufung": 2,
  "Pastille der Phasenenergie": 2,
  "Pastille der Phasenrisse": 2,
  "Pastille der Schreckensblitze": 2,
  "Pastille der Schreckensblumen": 2,
  "Pastille der Schärfung": 2,
  "Pastille der Seelensicht": 2,
  "Pastille der Zeitkontrolle": 2,
  "Pastille des Fliegens": 2,
  "Pastille des Wissens": 2,
  "Pastillenindikator": 172,
  "Pastillenpresse": 2500,
  "Pendel der Eiszeit": 2400,
  "Perfekter Cuslarsmaragd": 350,
  "Pergament der goldenen Einladung": 5,
  "Perle der Angst": 5,
  "Perle der Betörung": 25000,
  "Perle der großen Kraft": 2,
  "Perle der Kraft": 2,
  "Perlenquetsche": 2500,
  "Peststaude": 15,
  "Pfeil": 0,
  "Pfeilbeutel": 50,
  "Pflanzengift": 20,
  "Pflanzenkugel": 5,
  "Pflanzensamenbeutel": 0,
  "Phasenblitz": 10,
  "Phasenbrei": 5,
  "Phasenhämmerchen": 25,
  "Phasenkapsel": 25,
  "Phasenknoten": 599,
  "Phasenkugel": 5,
  "Phasenlanze": 2500,
  "Phasenplasma": 50,
  "Phasenschlüssel": 25,
  "Phasenschweiß": 5,
  "Phasenspeicherentlader": 500,
  "Phasensplitter": 4,
  "Phasenstrahlkanone": 50,
  "Phasentrank": 2,
  "Phasentropfen": 6,
  "Phasentruhe": 0,
  "Phasentruhe von Belpharia": 0,
  "Phasenwind-Regenerationstrank": 25,
  "Pigmentextraktor": 0,
  "Pilzquetsche": 21354,
  "Pilzsuppe": 5,
  "Pilztrank der Hornrückenverstecke": 5,
  "Pilztrank der Schotterwurmverstecke": 5,
  "Pilztrank der vergessenen Dinge": 5,
  "Pilztrank der vergrabenen Dinge": 5,
  "Pilztrank des Tempelglanzes": 5,
  "Pilzwürfel": 27,
  "Pinkes Osterei": 5,
  "Plan der Jerodar": 110,
  "Plan der Plünderer": 250,
  "Plüschtier des Auftragshauses": 5,
  "Podest": 0,
  "Podeststein": 0,
  "Portal-Indikator": 50,
  "Portalfeldgenerator": 350000,
  "Portalkristall von Beispieluser": 0,
  "Portalmaschine": 1000,
  "Portalstab": 3,
  "Portalstab-Bohrer": 0,
  "Portalstein": 5,
  "Portalwerfer": 0,
  "Poster des Auftragshauses": 0,
  "Postvogel": 7,
  "Postvogelkäfig": 25,
  "Pralinenschachtel": 1,
  "Priesterstab": 25,
  "Probierschachtel Sandlutscher": 5000,
  "Propellerblatt": 15,
  "präziser Mechanismus": 11,
  "Puppe der Rache": 40,
  "Puppe von Beispieluser": 80,
  "Pyramide der Seelen": 1,
  "Quallenglibber": 0,
  "Raketen-Schild von Pensal": 500,
  "Raketensplitter": 50,
  "Raptorschlitzer": 5000,
  "Reagenzglas mit Gewebewurm": 0,
  "Regenbogenstein": 0,
  "Regenbogenstrebe": 974,
  "Regenstab": 25,
  "reife Mango": 62,
  "Reparatur-Zange": 5,
  "Resistenz-Klumpen": 4,
  "riesiger Felsen": 10000,
  "riesiger Heiltrank": 5,
  "Riesiger Schokonikolaus": 5,
  "Ring der Erscheinung": 0,
  "Ring der Muse": "?",
  "Ring der Sternenfunken": 0,
  "Ring des Auftragskünstlers": 7500,
  "Ring des Blutdursts": 1750,
  "Ring des Fledderers": 6000,
  "Ring des Floristen": 6250,
  "Ring des Genies": 7500,
  "Ring des Gewebeanalytikers": 7000,
  "Ring des Gewebeforschers": 8750,
  "Ring des Goldräubers": 5000,
  "Ring des Großwildjägers": 5000,
  "Ring des Gruppenjägers": 4000,
  "Ring des Jägers": 4000,
  "Ring des Meteorologen": 8000,
  "Ring des Phasenverstehers": 5000,
  "Ring des Plünderers": 5000,
  "Ring des Sandsturms": 25000,
  "Ring des Sandwindes": 5,
  "Ring des Seelenverbinders": 5000,
  "Ring des Todes": 600,
  "Ring des Vulkans": 10,
  "Ring des Überfliegers": 55000,
  "Ritual der Befreiung": 652,
  "Ritual der selbsterfüllenden Prophezeiung": 5,
  "Ritualdolch": 775,
  "Robuster Knochen": 448,
  "Rohrbauteil": 0,
  "rosa Portalmaschine": 40000,
  "rosa Stein der Selbstheilung": 400000,
  "Rosafarbener Heilsplitter": "?",
  "rostige Nägel": 0,
  "Rostiger Eisenschild": 300,
  "rostiger Werkzeugkoffer": 0,
  "rostiges Schwert": 180,
  "Rotationsschild": 38000,
  "Rotbandwolle": 25,
  "Rote Bierkiste": "?",
  "Rote Karte (W11)": 5,
  "rote Korallengrütze": 5,
  "Rote Mütze": 0,
  "Rote Pappnase": 15,
  "Rote Perle des Wissens": 5000,
  "rote Portalmaschine": 1000,
  "rote Rose": 3,
  "rote Schnur": 1,
  "Rote Schriftrolle": 0,
  "rote Zauberkugel": 5,
  "roter Bergstein": 50,
  "Roter Fels": 25,
  "roter Felsedelstein": 5,
  "roter Fächer": 3500,
  "roter Heilzauber": 1,
  "roter Hering": 30,
  "roter Herzauber": 30,
  "roter Prisma-Kristall": 100,
  "roter Relokationszauber": 35,
  "roter Ring des Schutzes": 600,
  "Roter Wissensindikator": 75000,
  "roter Wurzelschild": 10000,
  "roter Zauberstaub": 280,
  "Rotes Ei": 5,
  "Rotes Heringsbuch": 1000,
  "rotes Kristallschneckenhaus": 125,
  "Rotes Torponschlangenei": 50,
  "Rotkellerschimmel": 20,
  "Rotsandschwert": 140,
  "Rubin": 277,
  "Ruheplatz": 4,
  "Rumvorrat der Sontra Fahr": 5,
  "Räuchermännchen": 2,
  "Rückangriff: Blitzschlag": 10,
  "Rückangriff: Schutzvernichtung": 5,
  "Rückangriff: Tarnvernichtung": 5,
  "Rückangriffszauber": 1,
  "Rüstung des Serums": 820,
  "Sack mit neuartigem Tierfutter": 0,
  "saftiger Apfel": 2,
  "Salthosianische Sternenuhr": 107,
  "salthosianischer Signalfeuerfisch": 42,
  "salthosianischer Signalflötenfisch": 10,
  "Salz der XY-Mutation": 282,
  "Salzbier aus der Saline": 16,
  "Salzbier von Beispielsponsor": 16,
  "Salzkaramellapfel": 0,
  "Salzkaramellfisch": 20,
  "Salzkristall": 7,
  "Salzpanzer": 15,
  "Salzwein aus der Saline": 16,
  "Salzwein von Beispielsponsor": 16,
  "Sandflammenstein": 24,
  "Sandkanone": 500,
  "Sandkleber": 5,
  "Sandlutscher": 5,
  "Sandorchidee": 25,
  "Sandorchidee-Samen": 1,
  "Sandranke": 8,
  "Sandring": 600,
  "Sandrose": 10,
  "Sandrüstung": 150,
  "Sandschwert": 100,
  "Sandstab": 15,
  "Sandsturm": 17000,
  "Sandwand": 160,
  "Sandwelle": 35,
  "Sandzange": 775,
  "sanfter Gewebewurm": 20,
  "Saubere Wolle": 0,
  "Savannengras": 10,
  "Schachtelmesserblatt": 1,
  "Schafschergerät": 0,
  "Schale mit Fisch-Kleber": 20,
  "Schale mit Larinit-Kleber": 1,
  "scharfer Phasentrank": 2,
  "scharfes Feueröl": 45,
  "Schattenflügel": 10,
  "Schattenglas": 150,
  "Schattenkaffee aus der Schwarzbrüherei": 16,
  "Schattenkaffee von Beispielsponsor": 16,
  "Schattenkralle": 150,
  "Schattenmoosextrakt": 0,
  "Schattenpanzer": 1120,
  "Schattenpulver": 1,
  "Schattensplitter": 0,
  "Schattenstein": 0,
  "Schatzkarte": 0,
  "Schatzkarte von Salthos": 75,
  "Schatztruhe": 0,
  "Schatzversteck": 5,
  "Schaufel der Forscher": 0,
  "Schaufel des Auftragshauses": 0,
  "Schaumblume": 10,
  "Scheibe der Kampfgebiete": 50,
  "Scherbe der Hoffnung": 2500,
  "Schere": 1,
  "Scherenschnitt von Beispiel-NPC": 2,
  "Schiffsbonsai der Sontra Fahr": 10,
  "Schild": 1,
  "Schild der Sonne": "?",
  "Schild der Untergegangenen": 1000,
  "Schild der Vernichtung": 5,
  "Schild von Narubia": 500,
  "Schild von Pensal": 500,
  "Schildkrötenpanzer": "?",
  "Schimmernelke": 7,
  "Schimmerstaub": 10,
  "Schlangengift": 30,
  "Schleifer für Spitzhacken": 0,
  "Schleifpulver": 2000,
  "Schleimhautfisch": 0,
  "Schleimwasser": 5,
  "Schleuderapparatur": 100,
  "Schleuderfalle": 10,
  "Schlichter Ring": 2750,
  "schlichter Schatten-Diamant": "?",
  "schlichter Schatten-Edelstein": "?",
  "schlichter Schatten-Kristall": 200,
  "Schlommkraut": 10,
  "Schlüssel der Festung": 20,
  "Schlüssel des Auftragshauses": 0,
  "Schlüssel für Zimmer 1": 10,
  "Schlüssel für Zimmer 2": 20,
  "Schlüssel für Zimmer 3": 50,
  "Schlüssel von Mister Lorper": 0,
  "Schmerzfalle": 0,
  "Schmetterklinge": 100,
  "Schmetterlingsflügel": 15,
  "Schmuggelware": 0,
  "Schnaps aus der Schwarzbrauerei": 16,
  "Schnaps von Beispielsponsor": 16,
  "Schnapsnasen Rudolph": 4,
  "Schneckenschleim": 1,
  "Schneeblume": 10,
  "Schneediamant": 1750,
  "Schneegurke": 40,
  "Schneemesser": 14,
  "Schneewurmfutter": 1666,
  "schnelle Flöte der Beförderung": 250,
  "Schockblitz": 30,
  "Schoko-Osterhase": 5,
  "Schoko-Weihnachtsmann": 5,
  "Schokohase": 1,
  "Schokohäschen": 1,
  "Schokoladen Osterhase": 5,
  "Schokoladenhase": 5,
  "Schotterflechte": 4,
  "Schreckensblume": 7,
  "schreckliches NPC: Beispiel-NPC": 0,
  "Schrein": 50,
  "Schreizauber": 90,
  "Schriftrolle der Auktionshalle": 4800,
  "Schriftrolle der Beobachtung": 500,
  "Schriftrolle der Börse": 48,
  "Schriftrolle der Gruppensuche": 104,
  "Schriftrolle der Kontrolltürme": 20,
  "Schriftrolle der Lebenden": 1000,
  "Schriftrolle der neuen Wesen": 0,
  "Schriftrolle der Shops": 40000,
  "Schriftrolle der Verräter": 10,
  "Schriftrolle des Schließfachs": 10,
  "Schrumpfzauber": 30,
  "Schutz der Geistlosen": 15,
  "Schutz der Händler": 60,
  "Schutz der mächtigen Händler": 96,
  "Schutzauflösung der Geistlosen": 9,
  "Schutzgeisternebel": 17000,
  "Schutzvernichtung": 1,
  "Schutzzauber": 180,
  "Schutzzauber: Leere": 50,
  "schwache Herbeirufung der Geistlosen": 70,
  "schwache Kontrolle der Zeit": 50,
  "schwache Lebenserweiterung": 15,
  "schwacher Beutezauber": 60,
  "schwacher Kampfunfähigkeitszauber": 25,
  "schwacher Schutzzauber": 25,
  "schwacher Tarnzauber": 50,
  "Schwarzbier aus der Schwarzbrauerei": 16,
  "Schwarzbier von Beispielsponsor": 16,
  "schwarze Magierrobe": 5000,
  "schwarze Rose": 2,
  "schwarze Zauberkugel": 0,
  "Schwarzeisen": 20,
  "schwarzer Diamant": 5,
  "Schwarzer Eiskristall": 2000,
  "Schwarzer Klumpen": 200,
  "schwarzer Prisma-Kristall": 100,
  "schwarzer Talisman": 1100,
  "Schwarzmilch aus der Schwarzmolkerei": 16,
  "Schwarzmilch von Beispielsponsor": 16,
  "Schwarzschild": 600,
  "Schwebender Eiskristall": 125,
  "schwebender Kristalldolch": 1500,
  "schwere Arbeitskluft": 300,
  "Schwert des Lichts": 775,
  "Seelenblatt des Äonenjägers": 0,
  "Seelenkapsel": 0,
  "Seelenkapselmixer": 65000,
  "blauer Seelenstaub": 0,
  "Seelenklinge": 10000,
  "Seelenkugel": 5,
  "Seelenkugelverbinder": 25000,
  "Seelenstein von Beispielopfer": 0,
  "Seelensteintotem": 5,
  "Seelenstoff": 25,
  "Seemannsgarn": 20,
  "Seetang-Portalstab": "?",
  "Seetanganzug": "?",
  "Seetangkleber": 8750,
  "Seetangpaste": 7500,
  "Seetangtorus": "?",
  "Seidenöl": 300,
  "Seilrolle": 0,
  "Seismograph": "?",
  "Sektflasche": 10,
  "seltsam riechende Steinmasse": 3500,
  "seltsamer Müll": 2,
  "seltsamer Trank": 2,
  "seltsames Gas": 690,
  "Serum des Todes": 80,
  "Serum-Schwert": 400,
  "Sicht der Diebesopfer": 25,
  "Sicht der Dinge": 13,
  "Sicht der Geistlosen": 20,
  "Sicht der Opfer": 100,
  "Sicht der Schutzlosen": 100,
  "Sicht der Schwäche": 5,
  "Sicht der Stärke": 12,
  "Sicht der völligen Schwäche": 5,
  "Sicht des Akademielimits": 23,
  "Sicht des Lebens": 10,
  "Siegel der Beute": 10,
  "Silberbarren": 170,
  "Silberdiadem": 500,
  "Silberfuchsfell": 15,
  "Silbergabel": 16,
  "silberne Jerodar-Halskette": 500,
  "silberner Ohrring": 0,
  "Silberner Schraubring": 20,
  "silberner Spektralwürfel": 25,
  "Silberrüstung": 910,
  "Silberschnee": 25,
  "Silberschwert": 610,
  "Silberstein-Erz": 50,
  "Silbersteinaxt": 500,
  "Siramücken-Orakel": 250,
  "Sitzkissen": 1,
  "Slofoy-Perle": 250,
  "Sockel der Erfahrung": 20000,
  "Sockel der Feuersbrunst": 500,
  "Sockel der Frostkälte": 5000,
  "Sockel der Genesung": 500,
  "Sockel der Heilung": 500,
  "Sockel der Spektralwürfel-Anreicherung": 25,
  "Sockel der Vergiftung": 30000,
  "Sockel der Zeitkontrolle": 500,
  "Sockel des Wissens": 900000,
  "solide Feuerscherbe": 0,
  "Sonnencreme": 50,
  "Sonnenfeuerblume": 15,
  "Sonnenstab": 50,
  "Sonnenstaub": 2,
  "Sonnenstrahl-Blume": 6,
  "Sorus-Kapsel": 10,
  "Speisekarte aus Blatenien": 5,
  "Spektralsäule": 12,
  "Spekulatius": "?",
  "Spiegel der Markthalle": 55000,
  "Spindeldornschlinge": 5,
  "Spindelmesser": 250,
  "Spiralpflanze": 5,
  "Spitzhacke": 10,
  "Spitzhacke der Forscher": 0,
  "Splitter der Erfahrung": 1,
  "Splitter der Genesung": 5000,
  "Sponsorgutschein": 0,
  "Spore des Wissens": 25,
  "Sprengkapsel": 0,
  "Sprengkopf": 0,
  "Sprengpockenkorn": 20,
  "Spritze mit Gegengift": 0,
  "Stab der Bergwiesen": 10,
  "Stab der brillianten Magie": "?",
  "Stab der Dunkelheit": 520,
  "Stab der Entgiftung": 50,
  "Stab der Feuerbälle": 100,
  "Stab der fremden Gedanken": 775,
  "Stab der großen Gruppenheilung": 50000,
  "Stab der großen Magie": 5,
  "Stab der Gruppenheilung": 50,
  "Stab der Heilung": 14000,
  "Stab der inneren Heilkraft": 1000,
  "Stab der Innovation": 775,
  "Stab der knisternden Heilung": 16000,
  "Stab der Lebensenergie": 25,
  "Stab der Magie": 500,
  "Stab der mächtigen Gruppenheilung": 25000,
  "Stab der Spiele": 1,
  "Stab der Wunder": 100,
  "Stab des Handels": 80,
  "Stab des Lichts": 500,
  "Stab des Wissens": 50,
  "stabile Chaossense": 150,
  "stabiler Energiesplitter": 650,
  "Stabilisator": 1300,
  "Stachel des Todes": 775,
  "Stachelrüstung": 2000,
  "Stachelwinde": 6,
  "Stahlanzug": 600,
  "Stahlanzug-Rückseite": 5,
  "Stahlanzug-Vorderseite": 155,
  "Stahlkäfig": 0,
  "Stahlkäfig mit Baby-Einflügler": 0,
  "Stahlnetz der Einflügler": 5000,
  "stark durchschlagende Armbrust": 5000,
  "starke Betörung der Geistlosen": 10,
  "Starke Gruppen-Betörung der Geistlosen": 150,
  "starke Kontrolle der Zeit": 100,
  "Starke Sicht der Opfer": 100,
  "Starke Sicht der reichen Opfer": 150,
  "starke Sicht des Lebens": 100,
  "starke, globale Betörung": 750,
  "Starker Diebstahlzauber": 2000,
  "starker Fernheilzauber": 1,
  "starker Gewebewurm": 30,
  "starker Gruppenheilzauber": 15,
  "starker Hautbrand": 25,
  "Starker Heilzauber": 44,
  "starker Jerodar-Diebstahlzauber": 25,
  "starker Kampfunfähigkeitszauber": 200,
  "starker Rückangriffszauber": 10,
  "starker Schutzzauber": 250,
  "starker Tarnzauber": 100,
  "starrende Essenz": 20,
  "Starreschutz-Zauber": 180,
  "Starrfalle": 1,
  "Statue der großen Kraft": 12000,
  "Statue der Kraft": 25,
  "Statue der Verteidigung": 125000,
  "Statue von Horikon": 5000,
  "Staubschleifer-Ei": 10,
  "Staubschleifer-Ei-Bier-Torte": 5,
  "Staubschleifer-Eierpunsch": 15,
  "Steak mit Augen": 5,
  "Stein der Geister": 0,
  "Stein der Intelligenz": 1,
  "Stein der Phasenselbstheilung": 2500,
  "Stein der Selbstheilung": 25,
  "Stein der Stärke": 150,
  "Stein des Fliegens": 150,
  "Stein des Lebens": 1000,
  "Stein des Todes": 5,
  "Steingas": 300,
  "Steingehirn": 25,
  "Steinherz": 7,
  "Steinhuhn-Ei": 10,
  "Steinkratzkäferschuppe": 5,
  "Steinschale": 50,
  "Steinschale mit Gift": 5,
  "Steinschleuder": 149,
  "Stepto-Waranzahn": 250,
  "Sternbeutel": 25,
  "Sternenband von Beispielspieler": 0,
  "Sternenfunke": 0,
  "Sternenfunkenkarte": 0,
  "Sternfunkelband von Beispielspieler": 25,
  "Sternfunkelfeuer": 50,
  "Sternfunkelschleife": 287,
  "Sternfunkelsphäre": 500,
  "Sternfunkelsäckchen": 0,
  "Sternfunkelvioline": 100,
  "Sternfunkelzauber": "?",
  "Sternmuschelstaub": 200000,
  "Sternmuschelstaubkorn": 200,
  "Steuerrad der Sontra Fahr": 726,
  "Stierhoden": 15,
  "Stillezauber des Auftragshauses": 0,
  "Stimmungsstein": 1,
  "Stolperfalle": 6,
  "strategischer Hinzauber": 50,
  "Strativar-Herz": 10,
  "stumpfes Baru-Schwert": 100,
  "Sumpfblume": 0,
  "Sumpfblumenextrakt": 0,
  "Sumpfgasbombe": 50,
  "Sumpfgastasche": 5000,
  "Suphasglas": 150,
  "Symbol der Hoffnung": 25000,
  "Symbol der Kälte": 25,
  "Symbol des Lebens": 10,
  "Symbol des Schutzes": 10,
  "Synergie-Indikator": 6000,
  "Säbel der Pironer": 10000,
  "Säge des Auftragshauses": 0,
  "Süßcreme-Osterkärtchen": 5,
  "Tafel der Besitztümer": 50,
  "Tafel der Charakterfähigkeiten": 50,
  "Tafel der Errungenschaften": 100,
  "Tagebuch Tag 125": 10,
  "Talisman der Betörung": "?",
  "Talisman der Betörung (Event)": 0,
  "Talisman der Blubberheilung": 34,
  "Talisman der Erfahrung": 6,
  "Talisman der Heilung": 5,
  "Talisman der Phasenenergie": 5,
  "Talisman der Taufluten": 25,
  "Talisman der Wissensflut": 16666,
  "Talisman der Wunder": 0,
  "Talisman der Zeitkontrolle": 5,
  "Talisman des Goldnebels": 1,
  "Talisman des maximalen Wissens": 42,
  "Talisman des Sonnentaus": 42,
  "Talisman des Wissens": 1500,
  "Tannenzapfen": 5,
  "Tarnbombe": 500,
  "Tarunium": 1,
  "Taschenknaller": 350,
  "Taschenschmelzofen": 2500,
  "Taschentuch": 4,
  "Taschenuhr": 5,
  "Taucheranzug": 500,
  "Tautropfen": 0,
  "Tee aus der Schwarzbrüherei": 16,
  "Tee von Beispielsponsor": 16,
  "Teichkiesel": 940,
  "Teidam-Fansticker": 12,
  "Tempelschleim": 4,
  "Tentakelschild": 166,
  "Tiefengas": 150,
  "Tiefenkraftwurzel": 27,
  "Tiefenkrautwurzel": 25,
  "Tiefensandwurzel": 25,
  "Tiefenschleimwurzel": 10,
  "Tiefensteinwurzel": 25,
  "Tiefenwurzelzauber": 150,
  "Tierfutter": 20,
  "Tierfuttersack": 0,
  "Tirrebmetall": 150,
  "Titanweste": 17000,
  "Todesgrotten-Erz": 10,
  "Todesgrotten-Molchextrakt": 1500,
  "tolle Glitzerkette": 1,
  "Tolloschein": 705,
  "Tonarranke": 7,
  "Tonstein": 13,
  "Tor der Bestechlichkeit": 50,
  "Tor der Knochen": 10,
  "Tor der Kombinationen": 10,
  "Tor der Steine": 10,
  "Tor der Vergänglichkeit": 10,
  "Torpon-Schuppe": 15,
  "Torponschuppenpanzer": 100000,
  "tote Seelenklinge": 100,
  "tote Wüstenmaus": 1,
  "toter Blattalisk": 5,
  "toter Blutwurm": 5,
  "toter Gewebewurm": 3,
  "toter Tar-Fisch": 1,
  "trainierter Feuervogel": 250,
  "Trank der Mutation": 61,
  "Trank der Nordpolarisierung": 5,
  "Trank der Ostpolarisierung": 5,
  "Trank der Pflanzensicht": 25,
  "Trank der Phasenrisse": 35,
  "Trank der Schneeausgrabung": 6,
  "Trank der verlorenen Dinge": 5,
  "Trank der Waldpflanzensicht": 9,
  "Trank der Welterkundung": 50,
  "Trank der Westpolarisierung": 3,
  "Trank der Zufallspolarisierung": 12,
  "Trank des Golddufts": 100,
  "Trankregal": 10,
  "trockenes Gestrüpp": 15,
  "Trockenwurmpanzer": 165,
  "Trockenwurmteppich": 1,
  "Tropfstein": 10,
  "Tropfsteinkristall": 0,
  "Turmaufgang": 20,
  "Türkisfeder": 0,
  "umfassende Clanfeindversteinerung": 3,
  "umfassende Schutzvernichtung": 2,
  "umfassende Todesgrottenverbannung": 7,
  "Umhang der Schatten": 320,
  "Umhang der Transparenz": 17000,
  "unausgefüllter Tolloschein": 700,
  "unbekannte Pflanzensamen": 1,
  "unfertiger Stein der Selbstheilung": 50,
  "Unfertiger Torponschuppenpanzer": 5000,
  "Unkraut": 7,
  "unreines Ingerium": 42,
  "Unterkunfts-Portal (Einrichtungsgegenstand)": 10,
  "Unterkunftsportal": 29,
  "Unterwelt-Trüffel": 5,
  "untote Pflanzensamen": 1,
  "untote Welkblume": 15,
  "untoter Knochen": 0,
  "unvollständige Kopiermaschine": 96,
  "uralter Geisterbonsai": 10,
  "Ursprung der Furcht": 300,
  "Urwaldklematis": 10,
  "Verbandskasten": 0,
  "Verbesserte Schneeschaufel": 0,
  "Verbundene Seelenkugel": 1250,
  "Verdammt dicke Sumpfgasbombe": 50,
  "vereinigte Seelenkapsel": 5,
  "verfeinerter Koloa-Kaffee": 4,
  "verhexter Fellhering": 9999,
  "verhexter Hundertflossenhering": 100100,
  "verhexter Regenbogenhering": 77777,
  "verhexter Zehnflossenhering": 10010,
  "verklebtes Bündel Tannennadeln": 2,
  "verpackter Baum": 0,
  "Verräter: Desintegration": 10,
  "Verräter: Schutzvernichtung": 5,
  "Verräter: Tarnauflösung": 2,
  "Verräter: Wellenblitz": 10,
  "verschlossene Kiste mit Heilzaubern": 0,
  "verschlossene Kiste mit Waren": 0,
  "Verschlossener Hundekäfig": 0,
  "versiegelter Brief": 0,
  "Versiegender Heilzauber": 8,
  "versiegender Phasennektar": 10,
  "versiegender Phasensaft": 10,
  "Versteinerte Nebelmagnolie": 20,
  "versteinerter Rindenspeer": 2500,
  "Vertinsfrucht": 10,
  "Vertinsglöckchen": 0,
  "Vertinskanne": 5000,
  "Verwalterin seltsamer Folianten": 5,
  "Verwirrungszauber": 10,
  "verzauberter Fellhering": 9999,
  "verzauberter Fisch-Kleber": 5,
  "verzauberter Hundertflossenhering": 100100,
  "verzauberter Regenbogenhering": 77777,
  "verzauberter Zehnflossenhering": 10010,
  "verzaubertes Wasser": 0,
  "verzögerter Rückruf": 15,
  "Violette Schriftrolle": 0,
  "Violetter Diamant": 2,
  "violetter Prisma-Kristall": 100,
  "violettes Glasschälchen": 60,
  "virenverseuchter Schleim": 1,
  "vollständiger Prisma-Kristall": 100,
  "Vorschlaghammer": 980,
  "Vulkangestein": 20,
  "Vulkanschwert": 350,
  "Vuvuzela (W11)": 5,
  "Wakrudbeutel": 35,
  "Wakrudpilz": 35,
  "Waldbodengoldblume": 50,
  "Waldschlurch-Cracker": 5,
  "Waldschlurchpanzer": 20,
  "Wandhalterung": 10,
  "Wasserbärenkralle": 7,
  "Wassererbse": 10,
  "Wegzauber": 20,
  "Wegzauber-Schutz": 104,
  "Weihnachts - Elch": 10,
  "Weihnachtsgeschenk": 0,
  "Weihnachtsplätzchen": 1,
  "Weihnachtsstern": 10,
  "Weihnachtstee": 16,
  "Weihnachtstörtchen": 1,
  "Wein aus der Schwarzbrauerei": 16,
  "Wein von Beispielsponsor": 16,
  "Weinlager": 5,
  "Weißblatt-Strauch": 4,
  "weiße Laubnelke": 7,
  "weiße Rose": 6,
  "weiße Schokolade": 0,
  "weiße Seerose": 5,
  "weißer Prisma-Kristall": 100,
  "weißes Öl": 150,
  "Weltenfragment": 250,
  "Weltenspalter": 150,
  "Weltensplitter": 100000,
  "Weltmeisterpraline": 0,
  "Werkstatt": 15,
  "Wetterkontroll-Kristall": 0,
  "Wetterzauber: Phaseninvasion": "?",
  "Wetterzauber: Raumkrümmung": 1000,
  "wiederbelebende Substanz": 0,
  "wilde Kletternelke": 14,
  "Wilisischer Glögg": 15,
  "Windbeutel des Auftragshauses": 0,
  "Winddistel": 42,
  "Wissenskapsel": 8,
  "Wissenszauber von Beispieluser": 0,
  "Wissenszauber: Auftragsbeziehungen": 5,
  "Wissenszauber: Auftragsplanung": 5,
  "Wissenszauber: Auftragsvertuschung": 5,
  "Wissenszauber: Ausgrabungswissen": 5,
  "Wissenszauber: Blutwissen": 5,
  "Wissenszauber: Chaosbotanik": 5,
  "Wissenszauber: Chaosmagie": 5,
  "Wissenszauber: Diebstahlschutzwissen": 5,
  "Wissenszauber: Gewebeforschung": 5,
  "Wissenszauber: Gold-Inspiration": 5,
  "Wissenszauber: Goldraub": 5,
  "Wissenszauber: Großwildjagd": 5,
  "Wissenszauber: Innere Macht": 5,
  "Wissenszauber: Inspiration": 5,
  "Wissenszauber: Jagd": 5,
  "Wissenszauber: Leichenfledderei": 5,
  "Wissenszauber: Mutationswissen": 5,
  "Wissenszauber: Pflanzenkunde": 5,
  "Wissenszauber: Phasenenergieeffizienz": 5,
  "Wissenszauber: Phasenenergiemaximierung": 5,
  "Wissenszauber: Phasenenergiespeicherung": 5,
  "Wissenszauber: Phasenverständnis": 5,
  "Wissenszauber: Polarisationsanpassung": 5,
  "Wissenszauber: Schatzjagd": 5,
  "Wissenszauber: Synergie-Inspiration": 5,
  "Wissenszauber: Verjagen": 5,
  "Wissenszauber: Vertreiben": 5,
  "Wissenszauber: Wissens-Inspiration": 5,
  "Wissenszauber: Zauberalchemie": 200,
  "Wissenszauber: Zaubertresorwissen": 5,
  "Wissenszauber: Zaubertruhenwissen": 5,
  "Wissenszauber: Zeit-Inspiration": 5,
  "Wissenszauber: Überzeugungskraft": 5,
  "Wolkenblume": 3,
  "Wolkenschlüssel": 25,
  "Wolkenstoff": 5,
  "Wolkenstoff-Kompressor": 2400,
  "Wolldecke": 0,
  "Wucherwurzelbaum": 80,
  "Wucherwurzelerde": 10,
  "wunderbares Wunderbällchen": 4,
  "Wunderkerze": 1,
  "Wunderkugel": 555,
  "wundersame Seelenkugel": 75,
  "Wurmfutter": 270,
  "Wurstbowle": 12,
  "Wurzelbogen der Erde": 377,
  "Würfelöl": 600,
  "Wüstenmaus-Teidam-Chutney": 5,
  "Wüstenschaufel": 0,
  "Zauber der Arbeiter-Erfahrung": 8,
  "Zauber der Archäologie": 5,
  "Zauber der Barriere": 25,
  "Zauber der Besinnung": 80,
  "Zauber der Diener": 5,
  "Zauber der Entstarrung": 8,
  "Zauber der Erfahrung": 5,
  "Zauber der Furcht": 7,
  "Zauber der gezielten Entladung": 3,
  "Zauber der globalen Stille": 30,
  "Zauber der globalen Versteinerung": 50,
  "Zauber der Globalzauberabwehr": 100,
  "Zauber der Gruppen-Leere": 5,
  "Zauber der Keuroner-Erfahrung": 8,
  "Zauber der Kämpfer-Erfahrung": 8,
  "Zauber der Leere": 150,
  "Zauber der lokalen Auferstehung": 2,
  "Zauber der Magier-Erfahrung": 8,
  "Zauber der Magieverlängerung": 10,
  "Zauber der Natla-Erfahrung": 8,
  "Zauber der Nordpolarisierung": 5,
  "Zauber der Offenbarung": 138,
  "Zauber der Onlo-Erfahrung": 8,
  "Zauber der Selbstheilung": 1,
  "Zauber der Serum-Erfahrung": 8,
  "Zauber der starken Vergiftung": 1,
  "Zauber der starken, lokalen Auferstehung": 15,
  "Zauber der Starre": 200,
  "Zauber der Stille": 35,
  "Zauber der Südpolarisierung": 5,
  "Zauber der Taruner-Erfahrung": 8,
  "Zauber der tiefen Explosion": 0,
  "Zauber der Tänzerinnen": 5,
  "Zauber der unbändigen Wut": 40,
  "Zauber der unsichtbaren Explosion": 75,
  "Zauber der Vergiftung": 25,
  "Zauber der Verpestung": 28,
  "Zauber der Versteinerung": 100,
  "Zauber der Wetterbeherrschung": 250,
  "Zauber der Wettererzeugung": 75,
  "Zauber der Wetterkontrolle": 75,
  "Zauber der Wiederbelebung": 0,
  "Zauber der Wiederherstellung": 500,
  "Zauber der Zauberer-Erfahrung": 8,
  "Zauber des Archäologiemeisters": 25,
  "Zauber des begrenzten Wissens": 8,
  "Zauber des Blutrauschs": 24,
  "Zauber des dringenden Notrufs": 50,
  "Zauber des dunklen Rituals": 50,
  "Zauber des langen Lebens": 56,
  "Zauber des schnellen Wissens": 8,
  "Zauber des sehr schnellen Wissens": 8,
  "Zauber des Vergessens": 1,
  "Zauber des zellulären Zerfalls": 10,
  "Zauberbrezel": 24,
  "Zauberbrötchen": 1,
  "Zauberfalle": 0,
  "Zauberfluch": 231,
  "Zauberhafter Torponschuppenpanzer": 100000,
  "Zauberkeks": 50,
  "Zauberkugel-Klebemaschine": 28000,
  "Zauberkugelpresse": 40000,
  "Zauberkästchen von Beispielsponsor": 0,
  "Zauberpolle": 20,
  "Zauberpuzzle": 155,
  "Zauberregal": 5,
  "Zaubertresor": 238,
  "Zaubertruhe": 0,
  "Zaubertruhe aus Bernstein": 0,
  "Zaubertruhe der Dunkelheit": 0,
  "Zaubertruhe der Eiswelt": 188,
  "Zaubertruhe der Flucht": 188,
  "Zaubertruhe der Schatten": 0,
  "Zaubertruhe des Auftragshauses": 0,
  "Zaubertruhe des Dunkelmorin": 0,
  "Zaubertruhe des Wasserfalls": 0,
  "Zaubertruhe des Weltenwandlers": 0,
  "Zaubertruhe von Beispieluser": 5,
  "Zaubertruhe von Pensal": 0,
  "Zauberöl: beflügelte Seelen": 0,
  "Zauberöl: explosive Goldnebel": 0,
  "Zauberöl: florale Lebenssaat": "?",
  "Zauberöl: flüsternde Flora": 0,
  "Zauberöl: funkelnde Sterne": 0,
  "Zauberöl: kleines Gold": "?",
  "Zauberöl: kreisende Sterne": 0,
  "Zauberöl: lebendige Schatten": 0,
  "Zauberöl: pulsierende Lebensenergie": 0,
  "Zauberöl: pyrogene Erfahrung": 0,
  "Zauberöl: roter Donner": 0,
  "Zauberöl: spontaner Geistesblitz": 0,
  "Zauberöl: tanzende Sterne": 0,
  "Zauberöl: verschwundene Halle": 0,
  "Zauberöl: zauberhafter Funkensturm": 0,
  "Zeichnung von Beispiel-NPC": 56,
  "Zeiger der Zeit": 5,
  "Zepter der Zeit": "?",
  "Zepter des Wetterforsches": 25,
  "Zerbrochene Flügelrüstung": 155,
  "zerbrochene Jerodar-Halskette": 100,
  "zerbrochene Lopaknuss": 1,
  "zerbrochenes Artefakt": 0,
  "zerfallener Sandring": 155,
  "Zielscheibe": 150,
  "Zimtstern": 5,
  "Zitternde Stahlschraube": 13,
  "Zuckerbromelie": 10,
  "Zuckerstange": 1,
  "Zuckerstangen": 1,
  "Zweihänder des dunklen Sees": 250,
  "Ölfasstasche": 5000,
  "Ölfischzahn": 5,
  "Ölpumpe": 10,
  "überspannter Bogen der Seelen": 3888,
  "Überwucherter Pilzwürfel": 1111,
};
